substitutions:
  name: ir-remote
  friendly_name: IR-Remote
  device_description: Universal WiFi IR Blaster Remote
  hardware_info: "TYSW-ESP8266"
  project_name: "SB-Inovations.IR-Remote"
  project_version: "0.0.2"

dashboard_import:
  package_import_url: github://bnevets27/ESPHome-Projects/globe-ir-remote.yaml@main
  import_full_config: true

esphome:
  name: ${name}
  friendly_name: "${friendly_name}"
  comment: "${device_description}"
  name_add_mac_suffix: true
  project:
    name: ${project_name}
    version: ${project_version}
  platform: ESP8266
  board: esp01_1m

time:
  - platform: sntp
    id: time_sntp
    timezone: "America/Toronto"

text_sensor:
  - platform: template
    name: "Hardware Info"
    entity_category: diagnostic
    update_interval: 24h
    lambda: return {"$hardware_info"};
  - platform: version
    name: "ESPHome Version"
  - platform: wifi_info
    ip_address:
      name: "ESP IP Adress"
      icon: mdi:ip-network-outline
    mac_address:
      name: "ESP MAC Adress"
      icon: mdi:network-outline
    ssid:
      name: "AP SSID"
      icon: mdi:access-point
    bssid:
      name: "AP MAC Address"
      icon: mdi:access-point

sensor:
  - platform: uptime
    name: "Uptime"
    id: sys_uptime
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: wifi_signal
    name: "Signal"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

debug:

api:

ota:
  - platform: esphome
    password: ${device_name}
    id: ota_esphome
  - platform: http_request
    id: ota_http_request

http_request:
  verify_ssl: false

captive_portal:

wifi:
  ap:

web_server:
  port: 80

logger:
  baud_rate: 0

status_led:
  pin:
    number: GPIO4

remote_receiver:
  id: my_remote
  pin:
    number: GPIO5
    inverted: true
  dump: all

remote_transmitter:
  pin: GPIO14
  carrier_duty_percent: 50%

binary_sensor:
  - platform: status
    name: Online Status
    id: ink_ha_connected
    entity_category: "diagnostic"
  - platform: gpio
    pin:
      number: GPIO13
      inverted: true
    name: "Underside Button"
    id: underside_button
    disabled_by_default: true
    on_click:
      min_length: 15s
      max_length: 60s
      then:
        button.press: factory_reset_all

switch:
  - platform: template
    name: "TV Power"
    optimistic: true
    assumed_state: true
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E09966
    turn_off_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E019E6

button:
  - platform: restart
    name: "Reboot"
    icon: mdi:power-cycle
    entity_category: diagnostic
  - platform: safe_mode
    name: "Safe Mode"
    entity_category: diagnostic
  - platform: factory_reset
    name: "Factory Reset - Wipe All"
    disabled_by_default: true
    id: factory_reset_all
    icon: mdi:delete-forever
    entity_category: diagnostic
  - platform: template
    name: Logitech Vol Up
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xF708
          command: 0xE51A

  - platform: template
    name: Logitech Vol Dw
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xF708
          command: 0xF10E
