substitutions:
  project_name: "Lenovo.SE341AC_ESP8266"
  project_version: "0.0.1"
  hardware_info: "Lenovo SE-341AC TYWE29 (ESP8266)"
  device_info: "N/A"
  restore_mode_relay: RESTORE_DEFAULT_ON
# Calibrations
  voltage_divider: "1726.380073800738"
  current_resistor: "0.0010996998497973922"
  current_multiply: "1.170994777892605"

esp8266:
  board: esp01_1m
  early_pin_init: false  # Prevent the physical relay flipping on reboot.
  
logger:
  baud_rate: 0 # (UART logging disabled due to cse7766 power mon chip)

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO03
      mode: INPUT_PULLUP
      inverted: true
    name: "Button"
    on_press:
      - switch.toggle: relay

sensor:
  - platform: hlw8012
    model: BL0937
    sel_pin:
      number: GPIO09
      inverted: true
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current_resistor: ${current_resistor}
    voltage_divider: ${voltage_divider}
    change_mode_every: 3
    update_interval: 10s

    current:
      name: "Amps"
      unit_of_measurement: A
      accuracy_decimals: 2
      filters:
        - multiply: ${current_multiply}

    voltage:
      name: "Voltage"
      unit_of_measurement: V
      accuracy_decimals: 1

    power:
      name: "Watts"
      id: plug_power
      accuracy_decimals: 0

  - platform: total_daily_energy
    name: "Daily Energy"
    power_id: plug_power
    unit_of_measurement: kWh
    filters:
      - multiply: 0.001  # Convert Wh to kWh

switch:
  - platform: gpio
    pin: GPIO013
    id: relay
    name: "Relay"
    on_turn_on:
      - output.turn_on: led_blue
    on_turn_off:
      - output.turn_off: led_blue

status_led:
  pin:
    number: GPIO01
    inverted: true

output:
  - platform: gpio
    pin:
      number: GPIO12
      inverted: true
    id: led_blue
