# Device Info:
# https://developer.tuya.com/en/docs/iot/tysw012-round-universal-remote-control?id=K9lnm617oupeb
# https://devices.esphome.io/devices/Sonoff-S31

# Relay Disabled

substitutions:
  name: "plug-s31"
  friendly_name: "Plug-S31 -"
  device_description: "Sonoff S31 Power Monitor"
  device_info: "N/A"
  hardware_info: "Disabled-Relay|ESP8266_1M|CSE7766"
  #hardware_info: "Removed-Relay|ESP8266_1M|CSE7766"
  #### The Project information is required for adoption to work in the Dashboard. ####
  project_name: "Sonoff-SBI.S31_Plug"
  project_version: "0.0.1"
  ### Device Settings ###
  restore_mode_relay: ALWAYS_ON
  
# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://bnevets27/ESPHome-Projects/devices/plugs/sonoff-s31-no_relay.yaml@main
  import_full_config: true

## Note: Package order matters, they are loaded top down so, lowerest in the list overrites values of above packages
packages:
  remote_package:
    url: https://github.com/bnevets27/ESPHome-Projects/
    ref: main
    files:
      - common/base-diagnostic.yaml
      - common/base-network.yaml
    refresh: 0d

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  comment: "${device_description}"
  project:
    name: "${project_name}"
    version: "${project_version}"
  name_add_mac_suffix: true

esp8266:
  board: esp12e
  early_pin_init: false  # Prevent the physical relay flipping on reboot.
  
logger:
  baud_rate: 0 # (UART logging disabled due interferes with cse7766 power mon chip)
  logs:
    sensor: DEBUG # (Overide any global setting, to VERBOSE will spamming the cse7766 sensors)

time:
  - platform: sntp #(required for total_daily_energy)
    id: my_time

uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button_side
    on_click:
      min_length: 15s
      max_length: 60s
      then:
        button.press: factory_reset_all

sensor:
  - platform: cse7766
    current:
      name: "Current"
      accuracy_decimals: 2
      filters:
        - throttle_average: 60s
    voltage:
      name: "Voltage"
      accuracy_decimals: 2
      filters:
        - throttle_average: 60s
    power:
      name: "Power"
      accuracy_decimals: 2
      id: my_power
      filters:
        - throttle_average: 60s
    energy:
      name: "Energy"
      accuracy_decimals: 2
      filters:
        - throttle: 60s
    apparent_power: #(only available with version 2024.3.0 or greater)
      name: "Apparent Power"
      filters:
        - throttle_average: 60s
    power_factor: #(only available with version 2024.3.0 or greater)
      name: "Power Factor"
      accuracy_decimals: 2
      filters:
        - throttle_average: 60s

  - platform: total_daily_energy #(Optional, not specific to cse7766)
    name: "Daily Energy"
    power_id: my_power
    accuracy_decimals: 2
    filters:
      - multiply: 0.001 ## convert Wh to kWh
    unit_of_measurement: kWh

switch:
  - platform: gpio
    name: "Relay"
    internal: true #set to true to hide from HA - see https://esphome.io/components/switch/#config-switch
    pin: GPIO12
    id: relay
    restore_mode: ${restore_mode_relay}
    
status_led:
  pin:
    number: GPIO13
    inverted: True
