debug:
  # update_interval: 10min # default 60 seconds
  
binary_sensor:
  - platform: status
    name: Online Status
    id: ink_ha_connected
    entity_category: "diagnostic"

text_sensor:
  - platform: template
    name: "Hardware Info"
    entity_category: diagnostic
    update_interval: 24h
    lambda: return {"$hardware_info"};
  - platform: version
    name: "ESPHome Version"
  - platform: wifi_info
    ip_address:
      name: "ESP IP Adress"
      icon: mdi:ip-network-outline
    mac_address:
      name: "ESP MAC Adress"
      icon: mdi:network-outline
    ssid:
      name: "AP SSID"
      icon: mdi:access-point
    bssid:
      name: "AP MAC Address"
      icon: mdi:access-point

sensor:
  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 60s
    entity_category: "diagnostic"
    unit_of_measurement: minutes
    filters:
      - lambda: return x / 60.0;

  - platform: wifi_signal
    name: Signal
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

button:
  - platform: restart
    name: "Reboot"
    icon: mdi:power-cycle
    entity_category: diagnostic
  - platform: safe_mode
    name: "Safe Mode"
    entity_category: diagnostic
  - platform: factory_reset
    name: "Factory Reset - Wipe All"
    disabled_by_default: true
    id: factory_reset_all
    icon: mdi:delete-forever
    entity_category: diagnostic
