esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  comment: "${device_description}"
  project:
    name: "${project_name}"
    version: "${project_version}"
  name_add_mac_suffix: True

time:
  - platform: homeassistant
    id: homeassistant_time
    
## OR
#time:
#  - platform: sntp
#    id: time_sntp
#    timezone: "America/Toronto"
