substitutions:
  project:
    name: Undefined.Project
    version: "0.0.1"
  hardware_info: Undefined Hardware

esphome:
  project:
    name: ${project_name}
    version: ${project_version}

text_sensor:
  - platform: template
    name: Hardware Info
    entity_category: diagnostic
    update_interval: 24h
    lambda: return {"$hardware_info"};
  - platform: version
    name: ESPHome Version
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: SSID  
    bssid:
      name: BSSID
    # scan_results:
    #   name: Wifi Latest Scan Results 

sensor:
  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: wifi_signal
    name: Signal
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

button:
  - platform: restart
    name: Reboot
    icon: mdi:power-cycle
    entity_category: diagnostic
  - platform: safe_mode
    name: "Safe Mode"
    entity_category: diagnostic

binary_sensor:
  - platform: status
    name: Online Status
    id: ink_ha_connected
    entity_category: "diagnostic"

debug:
  #update_interval: 10min # default 60 seconds
