  - platform: gpio
    pin:
      number: ${reset_button}
      inverted: true
    name: "Reset Button"
    disabled_by_default: true
    on_click:
      min_length: 15s
      max_length: 60s
      then:
        button.press: factory_reset_all

text_sensor:
  - platform: template
    name: "Hardware Info"
    entity_category: diagnostic
    update_interval: 24h
    lambda: return {"$hardware_info"};
  - platform: version
    name: "ESPHome Version"
  - platform: wifi_info
    ip_address:
      name: "ESP IP Adress"
      icon: mdi:ip-network-outline
    mac_address:
      name: "ESP MAC Adress"
      icon: mdi:network-outline
    ssid:
      name: "AP SSID"
      icon: mdi:access-point
    bssid:
      name: "AP MAC Address"
      icon: mdi:access-point
    # scan_results:
    #   name: Wifi Latest Scan Results

sensor:
  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: wifi_signal
    name: Signal
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

button:
  - platform: restart
    name: "Reboot"
    icon: mdi:power-cycle
    entity_category: diagnostic
  - platform: safe_mode
    name: "Safe Mode"
    entity_category: diagnostic
  - platform: factory_reset
    name: "Factory Reset - Wipe All"
    disabled_by_default: True
    id: factory_reset_all
    icon: mdi:delete-forever
    entity_category: diagnostic

binary_sensor:
  - platform: status
    name: Online Status
    id: ink_ha_connected
    entity_category: "diagnostic"

debug:
  #update_interval: 10min # default 60 seconds
