esphome:
  platform: ESP8266
  
packages:
  remote_package:
    url: https://github.com/bnevets27/ESPHome-Projects/
    ref: main
    files:
      - common/base-generic.yaml
      - common/base-diagnostic-8266.yaml
      - common/base-network.yaml
    refresh: 0d
