#substitutions:
#  project:
#    name: Undefined.Project
#    version: "0.0.1"
#  hardware_info: Undefined Hardware

#esphome:
#  name: "${name}"
#  friendly_name: "${friendly_name}"
#  comment: "${device_description}"
#  project:
#    name: "${project_name}"
#    version: "${project_version}"
#    name_add_mac_suffix: True

esphome:
hardware_info: "ESP8266"
  project:
    name: "SB-Inovations.Sonoff_S31"
    version: "0.0.1"
## Device Options ##
  restore_mode_relay: RESTORE_DEFAULT_ON
  reset_button: GPIO0

time:
  - platform: sntp
    id: time_sntp
    timezone: "America/Toronto"

## OR
# time:
#   - platform: homeassistant
#     id: homeassistant_time
