# This version has the relay ENABLED
substitutions:
  name: plug-s31
  friendly_name: Plug-S31
  device_description: "Sonoff S31 Power Monitor"

dashboard_import:
  package_import_url: github://bnevets27/ESPHome-Projects/devices/oem/sonoff-s31.yaml@main
  import_full_config: true

packages:
  device: !include common/devices/plugs/s31.yaml
  base: !include common/base-8266.yaml
